<?php

namespace AdvertBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllDescOrdered()
    {
        return $this->findBy([], ['id' => 'DESC']);
    }
}
